Resources:
  5CHackathonLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      CodeUri: ../bin
      Runtime: python3.9
      Timeout: 60
      Events:
        proxyAPI:
          Type: Api
          Properties:
            Path: /api/{proxy+}
            Method: ANY
