Resources:
  5CHackathonLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      CodeUri: ../src
      Runtime: python3.9
      Timeout: 60
      Events:
        proxyAPI:
          Type: Api
          Properties:
            Path: /5c-hack-api
            Method: ANY
